# Stage 1: Build the application using Maven
FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY cloudlb/pom.xml ./pom.xml
COPY cloudlb/src ./src
RUN mvn clean package

# Stage 2: Create the runtime image
FROM eclipse-temurin:21-jre-jammy
WORKDIR /app
COPY --from=build /app/target/cloudlb-1.0-SNAPSHOT.jar ./cloudlb.jar
EXPOSE 6869
CMD ["java", "-jar", "cloudlb.jar"]
